<a href="https://colab.research.google.com/github/mackenzieackerman/Linear_Algebra_Coding_projects/blob/main/takehomeexam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Initialize the preliminary code:


In [2]:
import numpy as np
from numpy import c_

ll = "loaded"

In [11]:
# create the matrix M:
M = np.matrix([[40/100, 50/100, 20/100, 0],
               [30/100, 0, 40/100, 0],
               [30/100, 0, 40/100, 0],
               [0, 50/100, 0, 1]])


In [12]:
x0 = np.matrix([[100], [200], [0], [0]])
x0

matrix([[100],
        [200],
        [  0],
        [  0]])

In [13]:
M*x0


matrix([[140.],
        [ 30.],
        [ 30.],
        [100.]])

In [14]:
# Compute where skiers are after one ski run:

(M**2)*x0

matrix([[ 77.],
        [ 54.],
        [ 54.],
        [115.]])

In [15]:
#  We can take powers of M using the ** operator.

#  So, M**2  * x0 is the same as  M * M * x0

M ** 4  * x0

matrix([[ 58.73],
        [ 38.46],
        [ 38.46],
        [164.35]])

In [22]:
#  We can take powers of M using the ** operator.

#  So, M**2  * x0 is the same as  M * M * x0

M ** 48  * x0

matrix([[7.04863641e-02],
        [4.61441570e-02],
        [4.61441570e-02],
        [2.99837225e+02]])

In [25]:
#  We can take powers of M using the ** operator.

#  So, M**2  * x0 is the same as  M * M * x0

M ** 2  * x0

matrix([[ 77.],
        [ 54.],
        [ 54.],
        [115.]])